/* eslint-disable no-console */
import { showLogger } from '@/constant/env';

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, comment?: string): void {
  if (!showLogger) return;

  // Get pathname safely to avoid hydration mismatch
  const pathname = typeof window !== 'undefined' ? window?.location.pathname : 'server-side';

  console.log(
    '%c ============== INFO LOG \n',
    'color: #22D3EE',
    `${pathname}\n`,
    `=== ${comment ?? ''}\n`,
    object
  );
}
