# Generated by Django 5.2.7 on 2025-10-15 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=10)),
                ('action_type', models.CharField(choices=[('API_CALL', 'API Call'), ('VOTE_SYNC', 'Vote Sync'), ('RESULTS_SYNC', 'Results Sync'), ('ADMIN_ACTION', 'Admin Action'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Additional data as JSON', null=True)),
                ('user', models.CharField(blank=True, help_text='User who performed action', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.CharField(help_text='UUID from backend', max_length=100, unique=True)),
                ('user_team', models.CharField(choices=[('team-a', 'Team 01'), ('team-b', 'Team 02'), ('team-c', 'Team 03'), ('team-d', 'Team 04')], max_length=10)),
                ('voted_for', models.CharField(choices=[('team-a', 'Team 01'), ('team-b', 'Team 02'), ('team-c', 'Team 03'), ('team-d', 'Team 04')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_identifier', models.CharField(help_text='User identifier from frontend', max_length=100)),
                ('synced_with_backend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VoteResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10, unique=True)),
                ('team_name', models.CharField(max_length=50)),
                ('vote_count', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('total_votes', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vote Result',
                'verbose_name_plural': 'Vote Results',
                'ordering': ['-vote_count'],
            },
        ),
    ]
